[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "v2-periphery/=lib/v2-periphery/",
  "@uniswap/universal-router/=lib/universal-router/",
  "@uniswap/permit2/=lib/universal-router/lib/permit2/"
]